### ISSUE TITLE
Польза паттерна Builder

### ISSUE THREAD

**Issue by alexmikhalevich** [edgarshmavonyan/PizzaFactory#1]
Зачем для такого объекта использовать паттерн Builder?
https://github.com/edgarshmavonyan/PizzaFactory/blob/cc18a07f67a7e2538e04d215cfada76cbfa5343f/pizza.h#L12

**Comment by edgarshmavonyan** [comment]
Попробую сделать сеттеры приватными и обращаться к ним через дружественные builder-ы

**Comment by edgarshmavonyan** [comment]
Пофиксил, жду ответа.
